// coupleProjects/TestCase/src/vue_components/App.vue
<template>
  <div class="sv-viewWrapper">
    <header-app></header-app>
    <main>
      <router-view></router-view>
    </main>
    <filter-app v-if="$route.path === '/'"></filter-app>
  </div>
</template>

<script>
  import Header from './MainComponents/Header';
  import { mapMutations, mapGetters } from 'vuex';
  import Vue from 'vue';
  import { store } from '../store';
  export default {
    components: {
        'header-app': Header
    },

  }
</script>

<style>

</style>

// coupleProjects/react-and-redux/src/App.js
import React, { Component } from 'react';
import { Provider } from 'react-redux';
import { BrowserRouter } from 'react-router-dom';


import Header from './Components/DefaultComponents/Header/Header';
import Main from './Components/DefaultComponents/Main/Main';
import Footer from './Components/DefaultComponents/Footer/Footer';

import store from './store';

class App extends Component {
  render() {
    return (
        <Provider store={store}>
            <BrowserRouter>
                <div className="App">
                    <Header />
                    <Main />
                    <Footer />
                </div>
            </BrowserRouter>
        </Provider>
    );
  }
}

export default App;
